htdocs/indicators/urls.py
from django.conf.urls import patterns, include, url

from .views import CollectedDataList, CollectedDataCreate, CollectedDataUpdate, CollectedDataDelete, IndicatorCreate, IndicatorDelete, IndicatorUpdate,\
    IndicatorList, IndicatorExport, CollectedDataExport


urlpatterns = patterns('',

    ###INDICATOR PLANING TOOL
    #Home
    url(r'^home/(?P<pk>\w+)/$', IndicatorList.as_view(), name='indicator_list'),

    #Indicator Report
    url(r'^report/(?P<program>\w+)/$', 'indicators.views.indicator_report', name='indicator_report'),
    url(r'^program_report/(?P<program>\w+)/$', 'indicators.views.programIndicatorReport', name='programIndicatorReport'),

    #Indicator Form
    url(r'^indicator_list/(?P<pk>\w+)/$', IndicatorList.as_view(), name='indicator_list'),
    url(r'^indicator_create/(?P<id>\w+)/$', 'indicators.views.indicator_create', name='indicator_create'),
    url(r'^indicator_add/(?P<id>\w+)/$', IndicatorCreate.as_view(), name='indicator_add'),
    url(r'^indicator_update/(?P<pk>\w+)/$', IndicatorUpdate.as_view(), name='indicator_update'),
    url(r'^indicator_delete/(?P<pk>\w+)/$', IndicatorDelete.as_view(), name='indicator_delete'),

    #Collected Data List
    url(r'^collecteddata/(?P<indicator>\w+)/$', CollectedDataList.as_view(), name='collecteddata_list'),
    url(r'^collecteddata/(?P<indicator>\w+)/(?P<program>\w+)/$', CollectedDataList.as_view(), name='collecteddata_list'),
    url(r'^collecteddata/(?P<indicator>\w+)/(?P<program>\w+)/(?P<agreement>\w+)/$', CollectedDataList.as_view(), name='collecteddata_list'),

    url(r'^collecteddata_add/(?P<program>\w+)/(?P<indicator>\w+)/$', CollectedDataCreate.as_view(), name='collecteddata_add'),
    url(r'^collecteddata_import/$', 'indicators.views.collecteddata_import', name='collecteddata_import'),
    url(r'^collecteddata_update/(?P<pk>\w+)/$', CollectedDataUpdate.as_view(), name='collecteddata_update'),
    url(r'^collecteddata_delete/(?P<pk>\w+)/$', CollectedDataDelete.as_view(), name='collecteddata_delete'),
    url(r'^collecteddata_export/(?P<program>\w+)/$', CollectedDataExport.as_view(), name='collecteddata_export'),

    #Indicator Data Report
    url(r'^data/(?P<id>\w+)/$', 'indicators.views.indicator_data_report', name='indicator_data_report'),
    url(r'^data/(?P<id>\w+)/(?P<program>\w+)/map/$', 'indicators.views.indicator_data_report', name='indicator_data_report'),
    url(r'^data/(?P<id>\w+)/(?P<program>\w+)/graph/$', 'indicators.views.indicator_data_report', name='indicator_data_report'),
    url(r'^data/(?P<id>\w+)/(?P<program>\w+)/table/$', 'indicators.views.indicator_data_report', name='indicator_data_report'),
    url(r'^data/(?P<id>\w+)/(?P<program>\w+)/$', 'indicators.views.indicator_data_report', name='indicator_data_report'),
    url(r'^export/(?P<program>\w+)/$', IndicatorExport.as_view(), name='indicator_export'),
    url(r'^export_data/(?P<indicator>\w+)/(?P<program>\w+)/$', CollectedDataExport.as_view(), name='indicator_data_export'),

    #ajax calls
    url(r'^service/(?P<service>[-\w]+)/service_json/', 'indicators.views.service_json', name='service_json'),
    url(r'^collected_data_table/(?P<indicator>[-\w]+)/(?P<program>[-\w]+)/', 'indicators.views.collected_data_json', name='collected_data_json'),

)

htdocs/tola/urls.py
from feed import views
from tola import views
from feed.views import UserViewSet, ProgramViewSet, SectorViewSet, ProjectTypeViewSet, OfficeViewSet, SiteProfileViewSet, AgreementViewSet, \
    CompleteViewSet, CountryViewSet, ProjectTypeOtherViewSet, IndicatorViewSet, ReportingFrequencyViewSet, TolaUserViewSet, IndicatorTypeViewSet, ObjectiveViewSet, DisaggregationTypeViewSet, LevelViewSet
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib.auth.models import User
from rest_framework.routers import DefaultRouter
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework import routers, serializers, viewsets
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

#REST FRAMEWORK
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'programs', ProgramViewSet)
router.register(r'sector', SectorViewSet)
router.register(r'projecttype', ProjectTypeViewSet)
router.register(r'office', OfficeViewSet)
router.register(r'siteprofile', SiteProfileViewSet)
router.register(r'country', CountryViewSet)
router.register(r'agreements', AgreementViewSet)
router.register(r'completes', CompleteViewSet)
router.register(r'projecttypeother', ProjectTypeOtherViewSet)
router.register(r'indicator', IndicatorViewSet)
router.register(r'reportingfrequency', ReportingFrequencyViewSet)
router.register(r'tolauser', TolaUserViewSet)
router.register(r'indicatortype', IndicatorTypeViewSet)
router.register(r'objective', ObjectiveViewSet)
router.register(r'disaggregationtype', DisaggregationTypeViewSet)
router.register(r'level', LevelViewSet)




urlpatterns = patterns('',
                        #rest framework
                        url(r'^api/', include(router.urls)),
                        url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

                        #index
                        url(r'^$', 'tola.views.index', name='index'),
                        #enable the admin:
                        url(r'^admin/', include(admin.site.urls)),
                        url(r'^(?P<selected_countries>\w+)/$', 'tola.views.index', name='index'),

                        #index
                        url(r'^dashboard/(?P<id>\w+)/(?P<sector>\w+)/$', 'tola.views.index', name='index'),

                        #base template for layout
                        url(r'^$', TemplateView.as_view(template_name='base.html')),

                        #ipt app specific urls
                        #url(r'^indicators/', include('indicators.urls')),

                        #enable admin documentation:
                        url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

                        #home
                        url(r'^contact', 'tola.views.contact', name='contact'),
                        url(r'^faq', 'tola.views.faq', name='faq'),
                        url(r'^documentation', 'tola.views.documentation', name='documentation'),

                        #app include of activitydb urls
                        url(r'^activitydb/', include('activitydb.urls')),

                        #app include of activitydb urls
                        url(r'^indicators/', include('indicators.urls')),

                        #app include of customdashboard urls
                        url(r'^customdashboard/', include('customdashboard.urls')),

                        #local login
                        url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
                        url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='login'),
                        url(r'^accounts/logout/$', 'tola.views.logout_view', name='logout'),

                        #accounts
                        url(r'^accounts/profile/$', 'tola.views.profile', name='profile'),
                        url(r'^accounts/register/$', 'tola.views.register', name='register'),

                        #Auth backend URL's
                        url('', include('django.contrib.auth.urls', namespace='auth')),
                        url('', include('social.apps.django_app.urls', namespace='social')),



)  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

htdocs/indicators/models.py
from django.db import models
from django.contrib import admin
from django.conf import settings
from activitydb.models import Program, Sector, SiteProfile, ProjectAgreement, ProjectComplete, Country, Office, Documentation, TolaUser
from datetime import datetime
from django.contrib.auth.models import User


class TolaTable(models.Model):
    name = models.CharField(max_length=255, blank=True)
    table_id = models.IntegerField(blank=True, null=True)
    owner = models.ForeignKey('auth.User')
    remote_owner = models.CharField(max_length=255, blank=True)
    url = models.CharField(max_length=255, blank=True)
    create_date = models.DateTimeField(null=True, blank=True)
    edit_date = models.DateTimeField(null=True, blank=True)

    def __unicode__(self):
        return self.name


class TolaTablesAdmin(admin.ModelAdmin):
    list_display = ('name','owner','url','create_date','edit_date')
    display = 'Tola Table'


class IndicatorType(models.Model):
    indicator_type = models.CharField(max_length=135, blank=True)
    description = models.TextField(max_length=765, blank=True)
    create_date = models.DateTimeField(null=True, blank=True)
    edit_date = models.DateTimeField(null=True, blank=True)

    def __unicode__(self):
        return self.indicator_type


class IndicatorTypeAdmin(admin.ModelAdmin):
    list_display = ('indicator_type','description','create_date','edit_date')
    display = 'Indicator Type'


class StrategicObjective(models.Model):
    name = models.CharField(max_length=135, blank=True)
    country = models.ForeignKey(Country, null=True, blank=True)
    description = models.TextField(max_length=765, blank=True)
    create_date = models.DateTimeField(null=True, blank=True)
    edit_date = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ('country','name')

    def __unicode__(self):
        return self.name

    def save(self):
        if self.create_date is None:
            self.create_date = datetime.now()
        super(StrategicObjective, self).save()


class StrategicObjectiveAdmin(admin.ModelAdmin):
    list_display = ('country','name')
    search_fields = ('country','name')
    display = 'Strategic Objectives'


class Objective(models.Model):
    name = models.CharField(max_length=135, blank=True)
    program = models.ForeignKey(Program, null=True, blank=True)
    description = models.TextField(max_length=765, blank=True)
    create_date = models.DateTimeField(null=True, blank=True)
    edit_date = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ('program','name')

    def __unicode__(self):
        return self.name

    def save(self):
        if self.create_date is None:
            self.create_date = datetime.now()
        super(Objective, self).save()


class ObjectiveAdmin(admin.ModelAdmin):
    list_display = ('program','name')
    search_fields = ('name','program')
    display = 'Objectives'

class Level(models.Model):
    name = models.CharField(max_length=135, blank=True)
    description = models.TextField(max_length=765, blank=True)
    create_date = models.DateTimeField(null=True, blank=True)
    edit_date = models.DateTimeField(null=True, blank=True)

    def __unicode__(self):
        return self.name

    def save(self):
        if self.create_date is None:
            self.create_date = datetime.now()
        super(Level, self).save()

class LevelAdmin(admin.ModelAdmin):
    list_display = ('name')
    display = 'Levels'


class DisaggregationType(models.Model):
    disaggregation_type = models.CharField(max_length=135, blank=True)
    description = models.CharField(max_length=765, blank=True)
    create_date = models.DateTimeField(null=True, blank=True)
    edit_date = models.DateTimeField(null=True, blank=True)

    def __unicode__(self):
        return self.disaggregation_type


class DisaggregationTypeAdmin(admin.ModelAdmin):
    list_display = ('disaggregation_type','description','create_date','edit_date')
    display = 'Disaggregation Type'


class DisaggregationLabel(models.Model):
    disaggregation_type = models.ForeignKey(DisaggregationType)
    label = models.CharField(max_length=765, blank=True)
    create_date = models.DateTimeField(null=True, blank=True)
    edit_date = models.DateTimeField(null=True, blank=True)

    def __unicode__(self):
        return self.label


class DisaggregationLabelAdmin(admin.ModelAdmin):
    list_display = ('disaggregation_type','label','create_date','edit_date')
    display = 'Disaggregation Label'


class DisaggregationValue(models.Model):
    disaggregation_label = models.ForeignKey(DisaggregationLabel)
    value = models.CharField(max_length=765, blank=True)
    create_date = models.DateTimeField(null=True, blank=True)
    edit_date = models.DateTimeField(null=True, blank=True)

    def __unicode__(self):
        return self.value


class DisaggregationValueAdmin(admin.ModelAdmin):
    list_display = ('disaggregation_label','value','create_date','edit_date')
    display = 'Disaggregation Value'


class ReportingFrequency(models.Model):
    frequency = models.CharField(max_length=135, blank=True)
    description = models.CharField(max_length=765, blank=True)
    create_date = models.DateTimeField(null=True, blank=True)
    edit_date = models.DateTimeField(null=True, blank=True)

    def __unicode__(self):
        return self.frequency


class ReportingFrequencyAdmin(admin.ModelAdmin):
    list_display = ('frequency','description','create_date','edit_date')
    display = 'Reporting Frequency'


class ReportingPeriod(models.Model):
    frequency = models.ForeignKey(ReportingFrequency)
    create_date = models.DateTimeField(null=True, blank=True)
    edit_date = models.DateTimeField(null=True, blank=True)

    def __unicode__(self):
        return self.frequency


class ReportingPeriodAdmin(admin.ModelAdmin):
    list_display = ('frequency','create_date','edit_date')
    display = 'Reporting Frequency'


class ExternalService(models.Model):
    name = models.CharField(max_length=255, blank=True)
    url = models.CharField(max_length=765, blank=True)
    feed_url = models.CharField(max_length=765, blank=True)
    create_date = models.DateTimeField(null=True, blank=True)
    edit_date = models.DateTimeField(null=True, blank=True)

    def __unicode__(self):
        return self.name


class ExternalServiceAdmin(admin.ModelAdmin):
    list_display = ('name','url','feed_url','create_date','edit_date')
    display = 'External Indicator Data Service'


class ExternalServiceRecord(models.Model):
    external_service = models.ForeignKey(ExternalService, blank=True, null=True)
    full_url = models.CharField(max_length=765, blank=True)
    record_id = models.CharField("Unique ID",max_length=765, blank=True)
    create_date = models.DateTimeField(null=True, blank=True)
    edit_date = models.DateTimeField(null=True, blank=True)

    def __unicode__(self):
        return self.full_url


class ExternalServiceRecordAdmin(admin.ModelAdmin):
    list_display = ('external_service','full_url','record_id','create_date','edit_date')
    display = 'Exeternal Indicator Data Service'


class Indicator(models.Model):
    owner = models.ForeignKey('auth.User')
    country = models.ForeignKey(Country, blank=True)
    indicator_type = models.ManyToManyField(IndicatorType, blank=True)
    level = models.ManyToManyField(Level, blank=True)
    objectives = models.ManyToManyField(Objective, blank=True, related_name="obj_indicator")
    strategic_objectives = models.ManyToManyField(StrategicObjective, blank=True, related_name="strat_indicator")
    name = models.CharField(max_length=255, null=True, blank=True)
    number = models.CharField(max_length=255, null=True, blank=True)
    source = models.CharField(max_length=255, null=True, blank=True)
    definition = models.TextField(null=True, blank=True)
    disaggregation = models.ManyToManyField(DisaggregationType, blank=True)
    baseline = models.CharField(max_length=255, null=True, blank=True)
    lop_target = models.CharField("LOP Target",max_length=255, null=True, blank=True)
    means_of_verification = models.CharField(max_length=255, null=True, blank=True)
    data_collection_method = models.CharField(max_length=255, null=True, blank=True)
    responsible_person = models.CharField(max_length=255, null=True, blank=True)
    method_of_analysis = models.CharField(max_length=255, null=True, blank=True)
    information_use = models.CharField(max_length=255, null=True, blank=True)
    reporting_frequency = models.ForeignKey(ReportingFrequency, null=True, blank=True)
    comments = models.TextField(max_length=255, null=True, blank=True)
    program = models.ManyToManyField(Program)
    sector = models.ForeignKey(Sector, null=True, blank=True)
    key_performance_indicator = models.BooleanField("Key Performance Indicator for this program?",default=False)
    approved_by = models.ForeignKey(TolaUser, blank=True, null=True, related_name="approving_indicator")
    approval_submitted_by = models.ForeignKey(TolaUser, blank=True, null=True, related_name="indicator_submitted_by")
    external_service_record = models.ForeignKey(ExternalServiceRecord, verbose_name="External Service ID", blank=True, null=True)
    create_date = models.DateTimeField(null=True, blank=True)
    edit_date = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ('create_date',)

    def save(self, *args, **kwargs):
        #onsave add create date or update edit date
        if self.create_date == None:
            self.create_date = datetime.now()
        self.edit_date = datetime.now()
        super(Indicator, self).save(*args, **kwargs)

    @property
    def name_clean(self):
        return self.name.encode('ascii', 'ignore')

    @property
    def objectives_list(self):
        return ', '.join([x.name for x in self.objectives.all()])

    @property
    def strategicobjectives_list(self):

htdocs/templates/indicators/collecteddata_confirm_delete.html
{% extends "base.html" %}
{% block page_title %}Collected Indicator Data Confirm Delete{% endblock %}

{% block content %}

<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete the collected data ?</p>
    <input type="submit" value="Confirm" />
</form>


{% endblock content %}

htdocs/templates/indicators/collecteddata_form.html
{% extends "base.html" %}
{% block bread_crumb %}
<ol class="breadcrumb">
  <li><a href="/indicators/home/0/">Indicators</a></li>
  <li><a href="/indicators/collecteddata/0/0/"> Data</a></li>
  <li class="active">Output Form</li>
</ol>

{% endblock %}
{% block page_title %}Collected Indicator Data{% endblock %}

{% block content %}
    <span style="float: right;"><a onclick="newPopup('https://docs.google.com/document/d/1sTBwo-oueQeH9NTGDXpbYZdlBTpRXBBK14IZUS0wN08/','Form Help/Guidance'); return false;" href="#" class="btn btn-sm btn-info">Form Help/Guidance</a></span>

    {% if form.errors %}
        <div class="help-block">
        {% for field in form %}
            {% for error in field.errors %}
                    <strong><i>{{ field.label }}</i> - {{ error|escape }}</strong>&nbsp;
            {% endfor %}
        {% endfor %}
        </div>
        {% for error in form.non_field_errors %}
            <div class="alert alert-error">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
	{% csrf_token %}
    {% load crispy_forms_tags %}
    {% crispy form %}

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            </div> <!-- /.modal-content -->
        </div> <!-- /.modal-dialog -->
    </div> <!-- /.modal -->

{% endblock content %}

htdocs/templates/indicators/collecteddata_import.html
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <title>Import from Tola Tables</title>
</head>
<body>
<script type="text/javascript" src="{{ STATIC_URL }}js/select2.min.js"></script>
<link href="{{ STATIC_URL }}css/select2.min.css" rel="stylesheet" />
<script type="text/javascript">
    //Searchable select option for service indicator
    $(document).ready(function() {
        /* add select2 js library to the indicator select box */
        $("#service_table").select2();
    });

</script>

<script type="text/javascript">
    var frm = $('#importForm');
    frm.submit(function () {
        $.ajax({
            type: frm.attr('method'),
            url: frm.attr('action'),
            data: frm.serialize(),
            success: function (data) {
                $("#alert-error").html("Success! ");
            },
            error: function(data) {
                $("#alert-error").html("Something went wrong!");
            }
        });
        return false;
    });
</script>

    <div class="modal-header">

    <div class="alert alert-error" id="alert-error">
        <strong>{{ error|escape }}</strong>
    </div>

    <h4 class="modal-title">{% block page_title %}Import Tola Table Evidence{% endblock %}</h4>

    </div>
    <div class="modal-body">
    {% if form.errors %}
        <div class="help-block">
        {% for field in form %}
            {% for error in field.errors %}
                    <strong><i>{{ field.label }}</i> - {{ error|escape }}</strong>&nbsp;
            {% endfor %}
        {% endfor %}
        </div>
        {% for error in form.non_field_errors %}
            <div class="alert alert-error">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
    <br/>
    <br/>
    <div class='jumbotron'>

        <h4>Import Indicator Evidence from <a href="http://tola-tables.mercycorps.org" target="_new">Tola Tables</a>.</h4>
        <p>Link one of your Tola Tables or a Table shared with you as your indicator evidence.</p>
        <div class="panel-body">
            <form class="form-horizontal" method="post" enctype="multipart/form-data" id="importForm" name="most" action="/indicators/collecteddata_import/" role="form">
              {% csrf_token %}

              <div class="form-group">
                  <label for="service_table">Tola Tables </label>
                  <select name="service_table" id="service_table" class="form-control">
                      {% for table in getTables.results %}
                      <option value="{{ table.id }}"> {{ table.owner.username }} - {{ table.name }} </option>
                      {% endfor %}
                  </select>
                  <span id="helpBlock" class="help-block">Type the name of the Table in the box above to search.</span>
              </div>

              <br/>
              <input type="submit" name="submit" value="save" class="btn btn-success">
            </form>
        </div>
    </div>

    </div>
    <div class="modal-footer">
       <button type="button" class="btn btn-default" data-dismiss="modal" onclick="window.location.reload();parent.location.reload();">Close</button>
    </div>

</body>
</html>

htdocs/templates/indicators/dashboard.html
{% extends "base.html" %} 
{% block page_title %}Dashboard{% endblock %} 

{% block content %}
	<p>Dashboard report on indicator status by Country and Program</p>

{% endblock content %}

htdocs/templates/indicators/data_report.html
{% extends "base.html" %}
{% block bread_crumb %}
<ol class="breadcrumb">
  <li><a href="/indicators/home/0/">Indicators</a></li>
  <li class="active">Reports</li>
</ol>

<div class="btn-group" role="group">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
    Indicator
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
            <li role="presentation"><a role="menuitem" tabindex="1" href="/indicators/data/0">--All--</a></li>
    {% for item in getIndicators %}
        <li role="presentation"><a role="menuitem" tabindex="1" href="/indicators/data/{{ item.id }}">{{ item.id}} - {{ item.name }}</a></li>
    {% endfor %}
  </ul>
</div>
<div class="btn-group" role="group">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-expanded="true">
    Programs
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu2">
      <li role="presentation"><a role="menuitem" tabindex="2" href="/indicators/data/0">--All--</a></li>
    {% for item in getPrograms %}
        <li role="presentation"><a role="menuitem" tabindex="2" href="/indicators/data/0/{{ item.id }}">{{ item.id}} - {{ item.name }}</a></li>
    {% endfor %}
  </ul>
</div>
<div class="btn-group" role="group">
  <button class="btn btn-default {% if 'table' in request.get_full_path %} active{%endif%}" onClick="location.href='/indicators/data/{{ id }}/{{ program }}/table/'" name="table">Table</button>&nbsp;
  <button class="btn btn-default {% if 'map' in request.get_full_path %} active{%endif%}" onClick="location.href='/indicators/data/{{ id }}/{{ program }}/map/'" name="map">Map</button>&nbsp;
  <button class="btn btn-default {% if 'graph' in request.get_full_path %} active{%endif%}" onClick="location.href='/indicators/data/{{ id }}/{{ program }}/graph/'" name="graph">Graph</button>
</div>
<br/>

{% endblock bread_crumb %}
{% load render_table from django_tables2 %}

{% block page_title %}Indicator Report{% endblock %}

{% block content %}

{% load crispy_forms_tags %}
{% crispy form form.helper %}
<br/>
{% if indicator_name %}
    <h4>Filtered by Indicator: {{ indicator_name }}</h4>
{% elif program_name %}
    <h4>Filtered by Program : {{ program_name }}</h4>
{% endif %}
{% if 'search' in request.get_full_path %}
    <p>{{ request.GET.urlencode }}</p>
{% endif %}
{% if "map" in request.get_full_path %}
    <style>
        #map { height: 350px; }
    </style>
    <p><b>Sites</b></p>
    <div id="map"></div>
    {% include "indicators/site_profile_map.html" %}
{% elif "graph" in request.get_full_path %}
    {% include "indicators/indicator_graphs.html" %}
{% else %}
    {% render_table table %}
{% endif %}
<br/>

<button type="submit" class="btn btn-success" onClick="location.href='/indicators/export_data/{{ id }}/{{ program }}/'">Export All</button>

{% endblock content %}

htdocs/templates/indicators/indicator_confirm_delete.html
{% extends "base.html" %}
{% block page_title %}Indicator Confirm Delete{% endblock %}

{% block content %}

<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete?</p>
    <input type="submit" value="Confirm" />
</form>


{% endblock content %}

htdocs/templates/indicators/indicator_form.html
{% extends "base.html" %}
{% block bread_crumb %}
<ol class="breadcrumb">
  <li><a href="/indicators/home/0/">Indicators</a></li>
  <li class="active">Indicator Form</li>
</ol>
{% endblock %}
{% block page_title %}Indicator{% endblock %}

{% block content %}
    <span style="float: right;"><a onclick="newPopup('https://docs.google.com/document/d/18QN7U6-b3AXmjL9fcHfFaxo1yisxuvpefGmsJTslJY4/,'Form Help/Guidance'); return false;" href="#" class="btn btn-sm btn-info">Form Help/Guidance</a></span>

    <script type="text/javascript" src="{{ STATIC_URL }}js/select2.min.js"></script>
    <link href="{{ STATIC_URL }}css/select2.min.css" rel="stylesheet" />
    <script type="text/javascript">
        //Searchable select option for service indicator
        $(document).ready(function() {
            /* add select2 js library to the indicator select box */
            $("#id_program").select2();
            $("#id_strategic_objectives").select2();
        });

    </script>

    {% if form.errors %}
        <div class="help-block">
        {% for field in form %}
            {% for error in field.errors %}
                    <strong><i>{{ field.label }}</i> - {{ error|escape }}</strong>&nbsp;
            {% endfor %}
        {% endfor %}
        </div>
        {% for error in form.non_field_errors %}
            <div class="alert alert-error">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
	{% csrf_token %}
    {% load crispy_forms_tags %}
    {% crispy form %}

{% endblock content %}

htdocs/templates/indicators/report.html
{% extends "base.html" %}
{% block bread_crumb %}
<ol class="breadcrumb">
  <li><a href="/indicators/home/0/">Indicators</a></li>
  <li class="active">Reports</li>
</ol>
<div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
    Programs
    <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
        <li role="presentation"><a role="menuitem" tabindex="-1" href="/indicators/report/0"> -- All --</a></li>
    {% for program in getPrograms %}
        <li role="presentation"><a role="menuitem" tabindex="-1" href="/indicators/report/{{ program.id }}">{{ program.gaitid}} - {{ program.name }}</a></li>
    {% endfor %}
    </ul>
</div>
<br/>
{% endblock bread_crumb %}
{% load render_table from django_tables2 %}

{% block page_title %}Indicator Report{% endblock %}

{% block content %}

{% load crispy_forms_tags %}
{% crispy form form.helper %}
<br/>

{% render_table get_agreements %}

<br/>

<button type="submit" class="btn btn-success" onClick="location.href=''">Export All</button>

{% endblock content %}

htdocs/templates/indicators/tool.html
{% extends "base.html" %} 
{% block page_title %}Indicator Planning Tool{% endblock %} 

{% block content %}
	<p>Create Indicator Plans for Programs</p>

{% endblock content %}